/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed-variant": "#574500",
        "on-tertiary-fixed": "#141f05",
        "primary": "#E8B923",
        "primary-container": "#C9A227",
        "on-secondary-fixed": "#062100",
        "secondary": "#a9d293",
        "inverse-primary": "#735c00",
        "surface-dim": "#0b1326",
        "primary-fixed": "#ffe088",
        "background": "#0b1326",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "outline-variant": "#4d4635",
        "surface-container": "#171f33",
        "on-tertiary-fixed-variant": "#3f4b2c",
        "on-secondary-fixed-variant": "#2d4f1e",
        "secondary-fixed": "#c5efad",
        "surface-container-low": "#131b2e",
        "secondary-fixed-dim": "#a9d293",
        "inverse-on-surface": "#283044",
        "on-surface": "#dae2fd",
        "on-primary-fixed": "#241a00",
        "tertiary": "#c5d4ab",
        "on-tertiary-container": "#3d492a",
        "error-container": "#93000a",
        "on-tertiary": "#293417",
        "secondary-container": "#2d4f1e",
        "on-secondary": "#173809",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#554300",
        "error": "#ffb4ab",
        "outline": "#99907c",
        "on-surface-variant": "#d0c5af",
        "on-error": "#690005",
        "tertiary-container": "#aab891",
        "surface-container-high": "#222a3d",
        "surface-variant": "#2d3449",
        "on-primary": "#3c2f00",
        "surface": "#0b1326",
        "primary-fixed-dim": "#e9c349"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "gutter": "16px",
        "margin-desktop": "40px",
        "margin-mobile": "20px",
        "card-gap": "12px",
        "container-margin": "16px",
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
